spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    username: ##username
    password: ##password
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/every_time